language: node_js
node_js:
  - "8.6.0"
install:
    - npm i
    - npm i -g coveralls
    - npm i -g istanbul
script:
    - mocha ./test/**/*.spac.js --exit
    - istambul cover ./node_modules/mocha/bin/_mocha ./test/**/*.spec.js --exit
    - cat ./coverage/lcov.info | coveralls
notification:
    email: false
